# Generated by Django 5.0.4 on 2024-05-02 10:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_image_alter_author_face'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('article', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='author',
            managers=[
                ('author', django.db.models.manager.Manager()),
            ],
        ),
    ]
