# Generated by Django 5.0.4 on 2024-05-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_author_options_alter_article_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['age'], 'verbose_name': 'Writer', 'verbose_name_plural': 'Writers'},
        ),
    ]
